name: Playwright Scheduled Test Pipeline

# Disable other triggers
trigger: none
pr: none

schedules:
  - cron: "0 9 * * *" # 5 AM UTC (Winter) = 5 AM GMT
    displayName: "Daily Trigger - 5 AM UK Time (GMT)"
    branches:
      include:
        - main
    always: true # Ensures it triggers even if no changes

variables:
  RunningOnPipeline: true
  envName: dcone

jobs:
  - job: test
    timeoutInMinutes: 0
    pool:
      name: "Digital Ocean"

    steps:
      # Install Node.js
      - task: NodeTool@0
        inputs:
          versionSpec: "16.x"
        displayName: "Install Node.js"

      # Install project dependencies
      - script: |
          npm ci
        displayName: "Install dependencies"

      # Install Playwright browsers with necessary dependencies
      - script: |
          npx playwright install --with-deps
        displayName: "Install Playwright browsers"

      # Run Playwright tests
      - script: |
          export RunningOnPipeline=$(RunningOnPipeline)
          export envName=$(envName)
          echo "Running on pipeline: $RunningOnPipeline"
          echo "Environment name: $envName"
          npx playwright test --grep '@dcone' --config=playwright.prod.config.ts
        displayName: "Run Playwright tests"

      # Publish Allure report
      - task: PublishAllureReport@1
        displayName: "Publish Allure report"
        condition: always()
